[qlik_replicate_servers]

qlik-prod-01 ansible_host=192.168.10.50
qlik-prod-02 ansible_host=192.168.10.51

[qlik_replicate_servers:vars]

ansible_user=oracle
ansible_become=true
ansible_become_method=sudo