---

- name: Create qlik group
  group:
    name: "{{ qlik_group }}"
    state: present

- name: Create qlik user
  user:
    name: "{{ qlik_user }}"
    group: "{{ qlik_group }}"
    home: "{{ qlik_install_dir }}"
    create_home: yes

- name: Create install directory
  file:
    path: "{{ qlik_install_dir }}"
    state: directory
    owner: "{{ qlik_user }}"
    group: "{{ qlik_group }}"

- name: Copy Qlik Replicate RPM
  copy:
    src: qlik-replicate.rpm
    dest: /tmp/qlik-replicate.rpm

- name: Install Qlik Replicate
  dnf:
    name: /tmp/qlik-replicate.rpm
    state: present